### ISSUE TITLE
运行出错。

### ISSUE THREAD

**Issue by weibut** [yonggekkk/openwrt_win64-ddns-cdnip#58]
直接运行{一条龙优选IP.exe}一闪而过。
在cmd下运行提示：
C:\Users\gr\Desktop\vs\CF优选IP一条龙版(WIN10-64)V23.12.29>一条龙优选IP.exe
------------------------------------------------------
甬哥Github项目  ：github.com/yonggekkk
甬哥Blogger博客 ：ygkkk.blogspot.com
甬哥YouTube频道 ：www.youtube.com/@ygkkk
------------------------------------------------------
一键优选多IP解析到CF单域名脚本   by OTC/甬哥侃侃侃
------------------------------------------------------
请在非代理的本地网络环境下运行

经检测，当前网络仅支持IPV4、无IPV6
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 467, in _make_request
  File "urllib3\connectionpool.py", line 1092, in _validate_conn
  File "urllib3\connection.py", line 635, in connect
  File "urllib3\connection.py", line 776, in _ssl_wrap_socket_and_match_hostname
  File "urllib3\util\ssl_.py", line 466, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 510, in _ssl_wrap_socket_impl
  File "ssl.py", line 517, in wrap_socket
  File "ssl.py", line 1075, in _create
  File "ssl.py", line 1346, in do_handshake
TimeoutError: _ssl.c:985: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 844, in urlopen
  File "urllib3\util\retry.py", line 470, in increment
  File "urllib3\util\util.py", line 39, in reraise
  File "urllib3\connectionpool.py", line 790, in urlopen
  File "urllib3\connectionpool.py", line 491, in _make_request
  File "urllib3\connectionpool.py", line 469, in _make_request
  File "urllib3\connectionpool.py", line 370, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.google.com', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "110.py", line 102, in <module>
  File "110.py", line 82, in is_google_reachable
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 532, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.google.com', port=443): Read timed out. (read timeout=5)
[20944] Failed to execute script '110' due to unhandled exception!

C:\Users\gr\Desktop\vs\CF优选IP一条龙版(WIN10-64)V23.12.29>

**Comment by yonggekkk** [comment]
是win10系统吗？
